repos:
-   repo: https://github.com/akkarapolk/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
repos:
- repo: https://github.com/akkarapolk/ansible/ansible-lint
  rev: v6.22.2
  hooks:
    - id: ansible-lint
